# Default values for cs.secreats.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
secret:
  name:

docbroker:
  certificate:
    password:
    aekpassphrase: Training_2026_25_4 
    trustpassword:
    pemCertPrivKey: 
    pemCertificate: 

docbase:
  password:
  
contentserver:
  installOwner:
    userName :
    password :
  globalRegistry :
    password:
  aek:
    algorithm: AES_256_CBC
    passphrase:
    oldPassphrase: 
  certificate:
    password:
    trustpassword:
    pemCertPrivKey: 
    pemCertificate: 

  install:
    appserver:
      admin:
        password:
    root:
      password:
kms:
  apiKey: <KMS_API_KEY>

openshifttls:
  enable:
  
### Database ###
database:
  userName: postgres
  password:
  certificate: ""

### Email Server ###
email:
  smtpUser:
  smtpPass:
  m365ClientId:
  m365ClientSecret:
  smtpSSLCertificate: |

### S3 Store ###
s3Store:
  s3StoreBaseUrl: 
  s3StoreCredentialID: nocredentials
  s3StoreCredentialKEY: nocredentials
  ### S3 Store ssl certificate, below value is for (otx-sgws01-l000.otxlab.net) change accordnigly ###
  certificate: ""

### Rest Store ###
restStore:
  restStoreBaseUrl: 
  restStoreCredentialID: 
  restStoreCredentialKEY: 
  ## rest Store ssl certificate, below value is for (azure blob store) change accordnigly ###
  azurecertificate: ""
  ## rest Store ssl certificate, below value is for (gcp blob store) change accordnigly ###
  gcpcertificate: ""

### newrelic ###
newrelic:
  license_key: 
  
 

# ingress TLS #
# tlscrt: <base64-encoded TLS certificate> as one line i.e. without any carriage returns or wrapped lines.
# tlscrt: <base64-encoded TLS key> as one line i.e. without any carriage returns or wrapped lines.
# use openssl utility or any other mechanism to generate key and certificate.
# openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout KEY_FILE.crt -out CERT_FILE.crt -subj "/CN=<domain name>/O=<domain name>"
# which generates a private key file "KEY_FILE.crt" and a certificate "CERT_FILE.crt" respectively for a given domain, convert content to base64.
# The below command generates a 2048-bit RSA private key (KEY_FILE.crt) and a X509 certificate (CERT_FILE.crt) valid for 365 days for host (cfcr-lab.bp-paas.otxlab.net).
# openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout KEY_FILE.crt -out CERT_FILE.crt -subj "/CN=cfcr-lab.bp-paas.otxlab.net/O=cfcr-lab.bp-paas.otxlab.net"
# NOTE: If the host(CN name) name specified during the certificate request process, doesn't match the host defined in your ingress route,
# your ingress controller displays a Kubernetes Ingress Controller Fake Certificate warning. Make sure your certificate and ingress route host names match.
ingress:
  tlscrt:
  tlskey:

### GCP Store credentials ###
gcpStore_credentials:

#Client app secrets are going to add here 
clients:
  drServiceAccountUser: dctmreports
  drServiceAccountPassword:
  preferencePassword:
  presetPassword:

documentumsearch:
  zk_password:
  solr_zk_password:
  solr_auth_password:

