# Default values for cs.secreats.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
secret:
  name: 

docbroker:
  certificate:
    password:
    aekpassphrase: Training_2026_25_4 
    trustpassword:
    pemCertPrivKey: 
    pemCertificate: 

docbase:
  password:
  
contentserver:
  installOwner:
    userName :
    password :
  globalRegistry :
    password:
  aek:
    algorithm: AES_256_CBC
    passphrase:
    oldPassphrase: 
  certificate:
    password:
    trustpassword:
    pemCertPrivKey: 
    pemCertificate: 

  install:
    appserver:
      admin:
        password:
    root:
      password:
kms:
  apiKey: <KMS_API_KEY>

openshifttls:
  enable:
  
### Database ###
database:
  userName: rdsmasteruser
  password: Fj*4W5<QDll5Ogq~?gITdu3HuPex
  certificate: ""

### Email Server ###
email:
  smtpUser:
  smtpPass:
  m365ClientId:
  m365ClientSecret:
  smtpSSLCertificate: |

### S3 Store ###
s3Store:
  s3StoreBaseUrl: 
  s3StoreCredentialID: nocredentials
  s3StoreCredentialKEY: nocredentials
  ### S3 Store ssl certificate, below value is for (otx-sgws01-l000.otxlab.net) change accordnigly ###
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICzDCCAbSgAwIBAgIJAOd7/dcwQv9dMA0GCSqGSIb3DQEBCwUAMBcxFTATBgNV
    BAMMDCoub3R4bGFiLm5ldDAeFw0xODAxMDMxODUyMTdaFw0yODAxMDExODUyMTda
    MBcxFTATBgNVBAMMDCoub3R4bGFiLm5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEP
    ADCCAQoCggEBAMbvOwEkeDIgua+tMEQkp7qAr59K9mzFjAlPp4Ng4dYTa5T8JH/A
    t28K7TGHj2hl2PZEhN177xtBl1U2LAufE5fbItqVQu1JPnYr4wrOdyA6Aiz7yR7w
    KblDiQdtz3BCLcQy+PURxfR9LQhY2AKxt4DUtpMbLG2FYwbCiOToW/yF1e2f0BaN
    MAOQxvqqZbCgZv3UagoROX+ZX7F3SZES6bGuPwufo80tGX+3ZgpblRSVf+z8ANIv
    zuNGL29OIYSBXg+vdH0lNb+XYCFd3tP3/hLRC992WSDibf4phgrD4VC1I9qUN7B1
    eN2iemVGtSs9jO/IW4zHBMN8UxG8PErqyj8CAwEAAaMbMBkwFwYDVR0RBBAwDoIM
    Ki5vdHhsYWIubmV0MA0GCSqGSIb3DQEBCwUAA4IBAQAUX6bZDeKKkMXxOV1DgQGq
    w4QUvtqYkxQhwPPXP9cbVaA6fJ359HzJkrggP63Ko9e+xcI9OiYMlZ6xfnkzMMUs
    EYw2l62BnxHXYPqN0h5NqDm1BT/UK4prHecRzyjw18RyQf80/1QQlSULCwfloWfh
    PFC9AyJv/CVpqTswi8+OmVyT7dIUHAoPFGUTyJ2U5jD7QyI1ifqN+QmN0aXH//QP
    glZkTA57ZvbLRwT8atpRh+a4VsDioTHuJAhc1C6H49kAq2wCd2vGUalvMPk2Q3p2
    YVui1RhsHuFm2UPApDFvtYvKXdm0Ma+jBoBqu1Ofita6kFLn6M4MGKHkiZ4qY8Gm
    -----END CERTIFICATE-----

### Rest Store ###
restStore:
  restStoreBaseUrl: 
  restStoreCredentialID: 
  restStoreCredentialKEY: 
  ## rest Store ssl certificate, below value is for (azure blob store) change accordnigly ###
  azurecertificate: ""

### newrelic ###
newrelic:
  license_key: 
  
 

# ingress TLS #
# tlscrt: <base64-encoded TLS certificate> as one line i.e. without any carriage returns or wrapped lines.
# tlscrt: <base64-encoded TLS key> as one line i.e. without any carriage returns or wrapped lines.
# use openssl utility or any other mechanism to generate key and certificate.
# openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout KEY_FILE.crt -out CERT_FILE.crt -subj "/CN=<domain name>/O=<domain name>"
# which generates a private key file "KEY_FILE.crt" and a certificate "CERT_FILE.crt" respectively for a given domain, convert content to base64.
# The below command generates a 2048-bit RSA private key (KEY_FILE.crt) and a X509 certificate (CERT_FILE.crt) valid for 365 days for host (cfcr-lab.bp-paas.otxlab.net).
# openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout KEY_FILE.crt -out CERT_FILE.crt -subj "/CN=cfcr-lab.bp-paas.otxlab.net/O=cfcr-lab.bp-paas.otxlab.net"
# NOTE: If the host(CN name) name specified during the certificate request process, doesn't match the host defined in your ingress route,
# your ingress controller displays a Kubernetes Ingress Controller Fake Certificate warning. Make sure your certificate and ingress route host names match.
ingress:
  tlscrt:
  tlskey:

### GCP Store credentials ###
gcpStore_credentials:

#Client app secrets are going to add here 
clients:
  drServiceAccountUser: dctmreports
  drServiceAccountPassword:
  preferencePassword:
  presetPassword:

documentumsearch:
  zk_password:
  solr_zk_password:
  solr_auth_password:

