{{- if eq .Values.ingress.enabled true }}
########################################################################
# Kubernetes Ingress for OTDS
# External Interface to provide a Fully Qualified Domain Name (FQDN)
# and enable secure HTTPS communication (if ingress.secret is provided)
########################################################################
{{- $serviceName := include "otds.ingress.service" . -}}
{{- $portNumber := .Values.otdsws.port -}}
{{- $prependPath := .Values.otdsws.ingress.prependPath -}}
{{- $paths := include "otds.ingress.paths" $ | splitList "," | rest -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{ else }}
apiVersion: extensions/v1beta1
{{ end }}
kind: Ingress
metadata:
  name: {{ template "otds.name" . }}-ingress
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
  annotations:
    # Description: Defines whether the ALB is internet-facing or internal.
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/subnets: subnet-028cf43e259bdebfc, subnet-04fa20cbc47830f86
    # subnet-028cf43e259bdebfc subnet-04fa20cbc47830f86 
    alb.ingress.kubernetes.io/target-type: 'ip'
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=1200
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=600,client_keep_alive.seconds=3600
    # Description: group.name annotation must be unique between deployments and namespaces.
    alb.ingress.kubernetes.io/group.name: dctm-internal-group
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    #alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    # Description: Defines whether the ALB uses IPv4, IPv6, or both.
    # Allowed values:
    #   - ipv4: ALB uses only IPv4 addresses.
    #   - dualstack: ALB uses both IPv4 and IPv6 addresses (subnets must have IPv6 CIDRs assigned).
    #   - dualstack-without-public-ipv4: Only applicable for internet-facing ALBs in public subnets.
    alb.ingress.kubernetes.io/ip-address-type: ipv4
    # Description: If Content Connect ingress is enabled in dctm-ingress, then uncomment the ssl-redirect annotation.
    # Also, if LSS is enabled, then uncomment the ssl-redirect annotation.
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    # Description: For secure connection, uncomment the following annotation.          
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-south-2:594171188460:certificate/a0b0f521-80be-4fe1-aa82-e58826fc5d53  
{{- if not (.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress") }}
{{- if .Values.ingress.class }}
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
{{- end }}
{{- end }}
{{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | squote }}
{{- end }}
spec:
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
{{- if .Values.ingress.class }}
  ingressClassName: {{ .Values.ingress.class }}
{{- end }}
{{- end }}
{{- if .Values.ingress.secret }}
  tls:
  - secretName: {{ .Values.ingress.secret }}
    hosts:
    - {{ .Values.otdsws.publicHostname }}
{{- end }}
  rules:
  - host: {{ .Values.otdsws.publicHostname }}
    http:
      paths:
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
{{- range $paths }}
{{- if $prependPath }}
      - path: {{ printf "/%s%s" $prependPath . }}
{{- else }}
      - path: {{ . }}
{{- end }}
        pathType: Prefix
        backend:
          service:
            name: {{ $serviceName }}
            port:
              number: {{ $portNumber }}
{{- end }}
{{ else }}
{{- range $paths }}
{{- if $prependPath }}
      - path: {{ printf "/%s%s" $prependPath . }}
{{- else }}
      - path: {{ . }}
{{- end }}
        backend:
          serviceName: {{ $serviceName }}
          servicePort: {{ $portNumber }}
{{- end }}
{{- end }}
---
{{- end }}